### ISSUE TITLE
Bug while preprocessing

### ISSUE THREAD

**Issue by XavierIsabel** [starmpcc/UniFL#1]
Hi! I am trying to reproduce the results shown in your article. While preprocessing the datasets, I am encountering multiple problems and bugs. Would their be any commits that haven't been made? A bug example is "preprocess_run.sh" calling the line "python main_setp1.py [...] ;" instead of "python main_step1.py [...] ;". Another one is the fact that the preprocess doesn't seem to consider the latest versions of the datasets.
Thank you!

**Comment by starmpcc** [comment]
Sorry, we noticed that our last bug fix commit was lost. 
I will create the bug fix again within this week as soon as possible. 
Related to the dataset version, please consider using MIMIC-IV 1.0.

FYI: There are a few imprecise logic sequences in the pre-processing codes, so we have migrated to [integrated-ehr-pipeline](https://github.com/Jwoo5/integrated-ehr-pipeline) for our current work.

Thank you for your interest in our work!

**Comment by starmpcc** [comment]
It's nearing completion, and it currently supports MIMIC-IV 2.0.
Unfortunately, my local server is under maintenance, so I'm unable to perform an end-to-end check at the moment.
I believe everything should work properly, but I'll test it all tomorrow and finalize it.

Update: I verified it finally works! If you have any problem, feel free to ask me!

Thank you!
