### ISSUE TITLE
ERROR WHEN RUN PREPROCESS

### ISSUE THREAD

**Issue by anvuvu03** [starmpcc/UniFL#2]
When i run prprocess folder, it always error not found {save path}/mimic3/descemb_whole/labevents.pkl' and not found {save_path}/mimic3_mv/npy/input_ids.npy'.., Can you help me ?

**Comment by anvuvu03** [comment]
![image](https://github.com/user-attachments/assets/9c92e98e-587a-45e2-b7d1-c100cb7ae0db)
![Uploading Screenshot 2024-10-25 111034.png…]()

**Comment by starmpcc** [comment]
Can you provide your environment variable? (The result of `$env`) ?

**Comment by anvuvu03** [comment]
![Screenshot 2024-10-25 111633](https://github.com/user-attachments/assets/6db6e83b-5f43-4bb7-b604-0074003dff34)
![Screenshot 2024-10-25 111651](https://github.com/user-attachments/assets/b9252cd8-dba2-4e66-b723-cb3c0fc4ff1a)

**Comment by starmpcc** [comment]
It seems that your command is incorrect.
When you execute the command
`$ bash preprocess_run.sh {MIMIC-III} {MIMIC-IV} {eICU} {save_path}`
you should replace `{save_path}` with the directory where you want to save the results.
Also, before executing the command, make sure that `{save_path}` points to an existing directory.

If you have any questions, feel free to ask.
And thank you for your interest in our research!

**Comment by anvuvu03** [comment]
i did as you said, but there is no descemb_whole folder in mimic3 and no input_ips.npy file in /mimic3_mv/npy
[Vu-Truong-An-TopCV.vn-241024.00040.pdf](https://github.com/user-attachments/files/17515885/Vu-Truong-An-TopCV.vn-241024.00040.pdf)
[HUST_PPT_template_2022_RED_4x3.pptx](https://github.com/user-attachments/files/17515886/HUST_PPT_template_2022_RED_4x3.pptx)
[Uploading IEEE_BrandedPresentationPPT_Template_A.pptx…]()

**Comment by anvuvu03** [comment]
i did as you said, but there is no descemb_whole folder in mimic3 and no input_ips.npy file in /mimic3_mv/npy
![Screenshot 2024-10-25 113459](https://github.com/user-attachments/assets/23eb05ba-d8e0-4445-b8e3-c3f431f84a99)
![Screenshot 2024-10-25 113513](https://github.com/user-attachments/assets/b987cfc2-1d8e-469e-93e2-f59e4aac39dc)

**Comment by anvuvu03** [comment]
![Screenshot 2024-10-25 114542](https://github.com/user-attachments/assets/698bdf15-9e55-4c85-98ce-4ae487656d64)
The files are not initialized which leads to the error as I mentioned in the top issue.

**Comment by starmpcc** [comment]
It seems like the first step of preprocessing (`main_step1.py`) was incorrectly terminated.
Can you share the full log, after doing the below steps?
1) Remove all contents within the `save_dir`.
2) Execute `bash preprocess_run.sh {MIMIC-III} {MIMIC-IV} {eICU} {save_path}`

**Comment by anvuvu03** [comment]
(unifl) backne@backne-Precision-3640-Tower:~/[physionet.org/files/UniFL/preprocess$](http://physionet.org/files/UniFL/preprocess$) bash preprocess_run.sh {MIMIC-III} {MIMIC-IV} {eICU} data
--2024-10-25 11:56:44--  https://www.hcup-us.ahrq.gov/toolssoftware/ccs/Multi_Level_CCS_2015.zip
Resolving [www.hcup-us.ahrq.gov](http://www.hcup-us.ahrq.gov/) ([www.hcup-us.ahrq.gov](http://www.hcup-us.ahrq.gov/))... 52.55.178.164, 54.86.175.62, 2600:1f18:6dc:c282:d4de:b071:7a42:c950, ...
Connecting to [www.hcup-us.ahrq.gov](http://www.hcup-us.ahrq.gov/) ([www.hcup-us.ahrq.gov](http://www.hcup-us.ahrq.gov/))|52.55.178.164|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: [https://hcup-us.ahrq.gov:443/toolssoftware/ccs/Multi_Level_CCS_2015.zip](https://hcup-us.ahrq.gov/toolssoftware/ccs/Multi_Level_CCS_2015.zip) [following]
--2024-10-25 11:56:45--  https://hcup-us.ahrq.gov/toolssoftware/ccs/Multi_Level_CCS_2015.zip
Resolving [hcup-us.ahrq.gov](http://hcup-us.ahrq.gov/) ([hcup-us.ahrq.gov](http://hcup-us.ahrq.gov/))... 44.196.83.239, 2600:1f18:6c7b:6b00:6e76:46c6:d93b:8cce
Connecting to [hcup-us.ahrq.gov](http://hcup-us.ahrq.gov/) ([hcup-us.ahrq.gov](http://hcup-us.ahrq.gov/))|44.196.83.239|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 111731 (109K) [application/zip]
Saving to: ‘data/cache/Multi_Level_CCS_2015.zip’

Multi_Level_CCS_2015.zip                           100%[===============================================================================================================>] 109,11K   111KB/s    in 1,0s    

2024-10-25 11:56:47 (111 KB/s) - ‘data/cache/Multi_Level_CCS_2015.zip’ saved [111731/111731]

--2024-10-25 11:56:47--  https://data.nber.org/gem/icd10cmtoicd9gem.csv
Resolving [data.nber.org](http://data.nber.org/) ([data.nber.org](http://data.nber.org/))... 198.71.6.39
Connecting to [data.nber.org](http://data.nber.org/) ([data.nber.org](http://data.nber.org/))|198.71.6.39|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2766948 (2,6M) [text/csv]
Saving to: ‘data/cache/icd10cmtoicd9gem.csv’

icd10cmtoicd9gem.csv                               100%[===============================================================================================================>]   2,64M   309KB/s    in 11s    

2024-10-25 11:56:59 (257 KB/s) - ‘data/cache/icd10cmtoicd9gem.csv’ saved [2766948/2766948]

--2024-10-25 11:56:59--  https://www.cms.gov/Medicare/Coding/ICD10/Downloads/2018-ICD-10-CM-General-Equivalence-Mappings.zip
Resolving [www.cms.gov](http://www.cms.gov/) ([www.cms.gov](http://www.cms.gov/))... 184.29.33.110, 2405:4800:10b:198::28a, 2405:4800:10b:182::28a
Connecting to [www.cms.gov](http://www.cms.gov/) ([www.cms.gov](http://www.cms.gov/))|184.29.33.110|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1114989 (1,1M) [application/zip]
Saving to: ‘data/cache/2018-ICD-10-CM-General-Equivalence-Mappings.zip’

2018-ICD-10-CM-General-Equivalence-Mappings.zip    100%[===============================================================================================================>]   1,06M  93,6KB/s    in 9,8s    

2024-10-25 11:57:09 (111 KB/s) - ‘data/cache/2018-ICD-10-CM-General-Equivalence-Mappings.zip’ saved [1114989/1114989]

create MIMIC3 ICU start!
length of PATIENTS.csv  :  46520
length of ICUSTAYS.csv  :  61532
length of DIAGNOSIS_ICD.csv  :  61532
length of ADMISSION.csv  :  58976
length of temp  : 49500
readmission value counts : readmission
0              43687
1               2708
dtype: int64
HOME HEALTH CARE             25.956867
HOME                         23.841349
SNF                          16.034753
REHAB/DISTINCT PART HOSP     13.261188
IN_ICU_MORTALITY              7.238516
LONG TERM CARE HOSPITAL       4.896795
IN_HOSPITAL_MORTALITY         3.562707
DISC-TRAN CANCER/CHLDRN H     1.292959
SHORT TERM HOSPITAL           0.904815
DISCH-TRAN TO PSYCH HOSP      0.863687
HOSPICE-HOME                  0.837982
LEFT AGAINST MEDICAL ADVI     0.583503
HOSPICE-MEDICAL FACILITY      0.336735
HOME WITH HOME IV PROVIDR     0.133666
OTHER FACILITY                0.123384
ICF                           0.102820
DISC-TRAN TO FEDERAL HC       0.025705
SNF-MEDICAID ONLY CERTIF      0.002570
Name: DISCHARGE_LOCATION, dtype: float64
Index(['DISC-TRAN CANCER/CHLDRN H', 'DISC-TRAN TO FEDERAL HC',
       'DISCH-TRAN TO PSYCH HOSP', 'HOME', 'HOME HEALTH CARE',
       'HOME WITH HOME IV PROVIDR', 'HOSPICE-HOME', 'HOSPICE-MEDICAL FACILITY',
       'ICF', 'IN_HOSPITAL_MORTALITY', 'IN_ICU_MORTALITY',
       'LEFT AGAINST MEDICAL ADVI', 'LONG TERM CARE HOSPITAL',
       'OTHER FACILITY', 'REHAB/DISTINCT PART HOSP', 'SHORT TERM HOSPITAL',
       'SNF', 'SNF-MEDICAID ONLY CERTIF'],
      dtype='object')
No Discharge                 51.983138
HOME                         16.402334
HOME HEALTH CARE             15.754569
SNF                           7.636943
REHAB/DISTINCT PART HOSP      4.079377
LONG TERM CARE HOSPITAL       1.475465
DISCH-TRAN TO PSYCH HOSP      0.596355
DISC-TRAN CANCER/CHLDRN H     0.529522
SHORT TERM HOSPITAL           0.395856
LEFT AGAINST MEDICAL ADVI     0.395856
HOSPICE-HOME                  0.372722
HOSPICE-MEDICAL FACILITY      0.131095
OTHER FACILITY                0.084826
ICF                           0.084826
HOME WITH HOME IV PROVIDR     0.064262
DISC-TRAN TO FEDERAL HC       0.010282
SNF-MEDICAID ONLY CERTIF      0.002570
Name: imminent_discharge, dtype: float64
Index(['DISC-TRAN CANCER/CHLDRN H', 'DISC-TRAN TO FEDERAL HC',
       'DISCH-TRAN TO PSYCH HOSP', 'HOME', 'HOME HEALTH CARE',
       'HOME WITH HOME IV PROVIDR', 'HOSPICE-HOME', 'HOSPICE-MEDICAL FACILITY',
       'ICF', 'LEFT AGAINST MEDICAL ADVI', 'LONG TERM CARE HOSPITAL',
       'No Discharge', 'OTHER FACILITY', 'REHAB/DISTINCT PART HOSP',
       'SHORT TERM HOSPITAL', 'SNF', 'SNF-MEDICAID ONLY CERTIF'],
      dtype='object')
average length:  6.250340590699946
dx freqeuncy [   1  403 1878 3428 5099 5930 5481 4779 3902 3180 2243 1427  738  301
   98   15]
max length:  15
min length:  0
The final MIMIC3 cohort pickle is saved at: data/mimic3_cohort.pkl
create eICU ICU start!
Unique patient unit stayid :  200859
final acuity class category dict_items([(0, 'Home'), (1, 'IN_HOSPITAL_MORTALITY'), (2, 'IN_ICU_MORTALITY'), (3, 'Nursing Home'), (4, 'Other'), (5, 'Other External'), (6, 'Other Hospital'), (7, 'Rehabilitation'), (8, 'Skilled Nursing Facility')])
Home                        59.131458
Skilled Nursing Facility    12.999186
IN_ICU_MORTALITY             5.487500
Other External               4.482644
Rehabilitation               4.327030
Other                        4.080340
Other Hospital               4.011581
IN_HOSPITAL_MORTALITY        3.432552
Nursing Home                 1.059742
Name: hospitaldischargelocation, dtype: float64
Index(['Home', 'IN_HOSPITAL_MORTALITY', 'IN_ICU_MORTALITY', 'Nursing Home',
       'Other', 'Other External', 'Other Hospital', 'Rehabilitation',
       'Skilled Nursing Facility'],
      dtype='object')
Home                        48.671552
No Discharge                30.948460
Skilled Nursing Facility     8.062366
Other                        3.055581
Other External               2.908411
Other Hospital               2.670768
Rehabilitation               2.375222
Nursing Home                 0.629693
Name: imminent_discharge, dtype: float64
Index(['Home', 'No Discharge', 'Nursing Home', 'Other', 'Other External',
       'Other Hospital', 'Rehabilitation', 'Skilled Nursing Facility'],
      dtype='object')
diganosis unique :  3736
Number of diagnosis with only ICD 10 code: 85
Number of more than one icd10 codes : 11
Number of icd10key_error_list : 41
Number of dx we have to find...786
Number of dx we have to find...684
Number of dx we have to find...567
Number of dx we have to find...508
Number of dx we have to find...0
The final eicu cohort pickle is saved at: data/eicu_cohort.pkl
create MIMIC4 ICU start!
HOME HEALTH CARE                25.868050
HOME                            24.760928
SKILLED NURSING FACILITY        18.662705
REHAB                            7.968566
CHRONIC/LONG TERM ACUTE CARE     6.538659
IN_ICU_MORTALITY                 6.342574
IN_HOSPITAL_MORTALITY            3.807053
HOSPICE                          2.037769
PSYCH FACILITY                   1.104106
ACUTE HOSPITAL                   0.838638
AGAINST ADVICE                   0.817521
OTHER FACILITY                   0.425352
ASSISTED LIVING                  0.126701
HEALTHCARE FACILITY              0.025642
Name: DISCHARGE_LOCATION, dtype: float64
Index(['ACUTE HOSPITAL', 'AGAINST ADVICE', 'ASSISTED LIVING',
       'CHRONIC/LONG TERM ACUTE CARE', 'HEALTHCARE FACILITY', 'HOME',
       'HOME HEALTH CARE', 'HOSPICE', 'IN_HOSPITAL_MORTALITY',
       'IN_ICU_MORTALITY', 'OTHER FACILITY', 'PSYCH FACILITY', 'REHAB',
       'SKILLED NURSING FACILITY'],
      dtype='object')
final acuity class category dict_items([(0, 'ACUTE HOSPITAL'), (1, 'AGAINST ADVICE'), (2, 'ASSISTED LIVING'), (3, 'CHRONIC/LONG TERM ACUTE CARE'), (4, 'HEALTHCARE FACILITY'), (5, 'HOME'), (6, 'HOME HEALTH CARE'), (7, 'HOSPICE'), (8, 'IN_HOSPITAL_MORTALITY'), (9, 'IN_ICU_MORTALITY'), (10, 'OTHER FACILITY'), (11, 'PSYCH FACILITY'), (12, 'REHAB'), (13, 'SKILLED NURSING FACILITY')])
No Discharge                    63.801321
HOME                            13.241727
HOME HEALTH CARE                11.431717
SKILLED NURSING FACILITY         6.247549
REHAB                            1.663700
CHRONIC/LONG TERM ACUTE CARE     1.009080
PSYCH FACILITY                   0.549036
HOSPICE                          0.538478
AGAINST ADVICE                   0.444961
ACUTE HOSPITAL                   0.242843
OTHER FACILITY                   0.206643
ASSISTED LIVING                  0.070892
HEALTHCARE FACILITY              0.007542
Name: imminent_discharge, dtype: float64
Index(['ACUTE HOSPITAL', 'AGAINST ADVICE', 'ASSISTED LIVING',
       'CHRONIC/LONG TERM ACUTE CARE', 'HEALTHCARE FACILITY', 'HOME',
       'HOME HEALTH CARE', 'HOSPICE', 'No Discharge', 'OTHER FACILITY',
       'PSYCH FACILITY', 'REHAB', 'SKILLED NURSING FACILITY'],
      dtype='object')
average length:  7.867100063350327
dx freqeuncy [  20  262 1136 2562 4071 5697 7280 8280 8831 8676 7366 5919 3796 1804
  533   63    2]
max length:  16
min length:  0
The final MIMIC4 cohort pickle is saved at: data/mimic4_cohort.pkl
INFO: Pandarallel will run on 8 workers.
INFO: Pandarallel will use Memory file system to transfer data between the main process and workers.
src :  mimic3 , table_name :  LABEVENTS
[0] Raw data shape:  (27854055, 9)
[1] Exclude useless columns:  (27854055, 7)
[2] Rename columns to ID, TIME
[3] Map ITEMID into descriptions:  (27854055, 7)
/home/backne/[physionet.org/files/UniFL/preprocess/preprocess_utils.py:103](http://physionet.org/files/UniFL/preprocess/preprocess_utils.py:103): SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['ID'] = df['ID'].astype('int')
/home/backne/[physionet.org/files/UniFL/preprocess/preprocess_utils.py:104](http://physionet.org/files/UniFL/preprocess/preprocess_utils.py:104): SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['TIME'] = pd.to_datetime(df['TIME'])
/home/backne/[physionet.org/files/UniFL/preprocess/preprocess_utils.py:110](http://physionet.org/files/UniFL/preprocess/preprocess_utils.py:110): SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time_fil['TIME'] = (time_fil['TIME'] - time_fil['INTIME']).astype('timedelta64[m]')
/home/backne/[physionet.org/files/UniFL/preprocess/preprocess_utils.py:111](http://physionet.org/files/UniFL/preprocess/preprocess_utils.py:111): SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time_fil.drop(columns=['INTIME', 'INTIME+12hr'], inplace=True)
[4] Filter ID,TIME by ICUSTAY ID,TIME:  (2151467, 7)
[5] Filter null columns:  (2151467, 7)
[6] Filter rows where ITEMID == nan:  (2151467, 7)

src :  mimic3 , table_name :  PRESCRIPTIONS
/home/backne/[physionet.org/files/UniFL/preprocess/main_step1.py:33](http://physionet.org/files/UniFL/preprocess/main_step1.py:33): DtypeWarning: Columns (11) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(os.path.join(src_path, table_name) + ".csv")
[0] Raw data shape:  (4156450, 19)
[1] Exclude useless columns:  (4156450, 13)
[2] Rename columns to ID, TIME
[3] Map ITEMID into descriptions:  (4156450, 13)
/home/backne/[physionet.org/files/UniFL/preprocess/preprocess_utils.py:103](http://physionet.org/files/UniFL/preprocess/preprocess_utils.py:103): SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['ID'] = df['ID'].astype('int')
/home/backne/[physionet.org/files/UniFL/preprocess/preprocess_utils.py:104](http://physionet.org/files/UniFL/preprocess/preprocess_utils.py:104): SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['TIME'] = pd.to_datetime(df['TIME'])
/home/backne/[physionet.org/files/UniFL/preprocess/preprocess_utils.py:110](http://physionet.org/files/UniFL/preprocess/preprocess_utils.py:110): SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time_fil['TIME'] = (time_fil['TIME'] - time_fil['INTIME']).astype('timedelta64[m]')
/home/backne/[physionet.org/files/UniFL/preprocess/preprocess_utils.py:111](http://physionet.org/files/UniFL/preprocess/preprocess_utils.py:111): SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time_fil.drop(columns=['INTIME', 'INTIME+12hr'], inplace=True)
[4] Filter ID,TIME by ICUSTAY ID,TIME:  (367389, 13)
[5] Filter null columns:  (367389, 13)
[6] Filter rows where ITEMID == nan:  (367389, 13)

src :  mimic3 , table_name :  INPUTEVENTS
/home/backne/[physionet.org/files/UniFL/preprocess/main_step1.py:28](http://physionet.org/files/UniFL/preprocess/main_step1.py:28): DtypeWarning: Columns (7,9,17,20,21) have mixed types. Specify dtype option on import or set low_memory=False.
  pd.read_csv(os.path.join(src_path, table_name) + "_CV.csv"),
[0] Raw data shape:  (21146926, 38)
[1] Exclude useless columns:  (21146926, 29)
[2] Rename columns to ID, TIME
[3] Map ITEMID into descriptions:  (21146926, 29)
/home/backne/[physionet.org/files/UniFL/preprocess/preprocess_utils.py:103](http://physionet.org/files/UniFL/preprocess/preprocess_utils.py:103): SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['ID'] = df['ID'].astype('int')
/home/backne/[physionet.org/files/UniFL/preprocess/preprocess_utils.py:104](http://physionet.org/files/UniFL/preprocess/preprocess_utils.py:104): SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['TIME'] = pd.to_datetime(df['TIME'])
preprocess_run.sh: line 8: 34475 Killed                  python main_step1.py --mimic3_path $mimic3_path --mimic4_path $mimic4_path --eicu_path $eicu_path --save_path $save_path
Traceback (most recent call last):
  File "/home/backne/[physionet.org/files/UniFL/preprocess/main_step2.py](http://physionet.org/files/UniFL/preprocess/main_step2.py)", line 531, in <module>
    main()
  File "/home/backne/[physionet.org/files/UniFL/preprocess/main_step2.py](http://physionet.org/files/UniFL/preprocess/main_step2.py)", line 452, in main
    df = complete_dataframe(src, table_names, config, args.save_path)
  File "/home/backne/[physionet.org/files/UniFL/preprocess/main_step2.py](http://physionet.org/files/UniFL/preprocess/main_step2.py)", line 23, in complete_dataframe
    lab = pd.read_pickle(
  File "/home/backne/Tools/anaconda3/envs/unifl/lib/python3.9/site-packages/pandas/io/pickle.py", line 187, in read_pickle
    with get_handle(
  File "/home/backne/Tools/anaconda3/envs/unifl/lib/python3.9/site-packages/pandas/io/common.py", line 795, in get_handle
    handle = open(handle, ioargs.mode)
FileNotFoundError: [Errno 2] No such file or directory: 'data/mimic3/descemb_whole/LABEVENTS.pkl'
Traceback (most recent call last):
  File "/home/backne/[physionet.org/files/UniFL/preprocess/split_for_FL.py](http://physionet.org/files/UniFL/preprocess/split_for_FL.py)", line 126, in <module>
    main()
  File "/home/backne/[physionet.org/files/UniFL/preprocess/split_for_FL.py](http://physionet.org/files/UniFL/preprocess/split_for_FL.py)", line 43, in main
    fold_mimic3 = pd.read_csv(
  File "/home/backne/Tools/anaconda3/envs/unifl/lib/python3.9/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/backne/Tools/anaconda3/envs/unifl/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 680, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/backne/Tools/anaconda3/envs/unifl/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 575, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/backne/Tools/anaconda3/envs/unifl/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 934, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/home/backne/Tools/anaconda3/envs/unifl/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1218, in _make_engine
    self.handles = get_handle(  # type: ignore[call-overload]
  File "/home/backne/Tools/anaconda3/envs/unifl/lib/python3.9/site-packages/pandas/io/common.py", line 786, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/mimic3/fold/fold_100.csv'
processing: data/mimic3_mv/npy/input_ids
Traceback (most recent call last):
  File "/home/backne/[physionet.org/files/UniFL/preprocess/split_npy.py](http://physionet.org/files/UniFL/preprocess/split_npy.py)", line 47, in <module>
    main()
  File "/home/backne/[physionet.org/files/UniFL/preprocess/split_npy.py](http://physionet.org/files/UniFL/preprocess/split_npy.py)", line 37, in main
    arr = np.load(
  File "/home/backne/Tools/anaconda3/envs/unifl/lib/python3.9/site-packages/numpy/lib/npyio.py", line 390, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'data/mimic3_mv/npy/input_ids.npy'

**Comment by starmpcc** [comment]
```
preprocess_run.sh: line 8: 34475 Killed python main_step1.py --mimic3_path $mimic3_path --mimic4_path $mimic4_path --eicu_path $eicu_path --save_path $save_path
```

This indicates that the Python process running main_step1.py was terminated without a stack trace. 
It seems to be an out-of-memory (OOM) issue. 
Could you share your hardware specs?

If reproducing the preprocessing on your hardware seems unlikely, I'll share the preprocessing results.

**Comment by anvuvu03** [comment]
maybe my capacity is overloaded, please share the preprocessing results, please!!!

**Comment by starmpcc** [comment]
I'm now executing the preprocessing codes.
Can you share your email address?

**Comment by anvuvu03** [comment]
my email: an.vt213792@sis.hust.edu.vn

**Comment by starmpcc** [comment]
I'll send it after it finished.
Again, thank for your interest in my research!
